---
sudo: false
addons:
  coverity_scan:
    project:
      description: Build submitted via Travis CI
      name: maxmind/GeoIP2-java
    notification_email: dev-ci@maxmind.com
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true compile
    branch_pattern: .*coverity.*
language: java
jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9
env:
  global:
    - secure: NZPWyoQ7lDzSMf6zAUxXNRgwPIWGAIN6eDgTD/vnFxOPYTJX8HEvIAEuoKAqajmJMqRwUl4D1s/cANBY8+IV//KDNiOZY1Hr070Wf2FIrAyxZ13sR3YVHzK6isKF6ISgVub2qyr028Wu1y1Qv2ggx6pRvRfCIBpth3r4l4sKeQU=
    - secure: VE86FgkS8MYUX1MpYiVpPCH7Zpyp9lysc3ewBS+QCmfh8dL2+GUPZRkgnQWw+k8vjD9RRkxmV7qQ9+FHTwIgw+X9jevP+mLQYeJhFKMO9Ftoq+W0kZkcg+BdAn4ATko/LJSHcKhtcdEw0+tQYlHFArf54nzgx/5ZR55fdZqCkbk=
before_install:
  - sudo apt-get install -y nodejs
  - npm install -g snyk
install:
  - mvn install -DskipTests=true -Dgpg.skip=true
  - snyk test --org=maxmind
after_success:
  - mvn clean cobertura:cobertura coveralls:report
  - "if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_JDK_VERSION == 'oraclejdk9' ]]; then snyk monitor --org=maxmind --project-name=maxmind/GeoIP2-java; fi"
notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "IPTl7X8II+1xqMfOdmoqXOMJXXv3Ej6w7RkfriEQXL2KEjOUXYsP3MeJZ7O86ZA1R1Rpq9wn0x2EpRiyIFa+MWtxFU1LlHFSDsW0hO7X5Jjkw96riWLlNhwLi8UDJdZg8GPzTq/cMY0MCpYrjtN9w5kDQRHDA8s9dyUXPZ4L+iE=\n"
